### ISSUE TITLE
CentOS 7 bug?

### ISSUE THREAD

**Issue by cdenneen** [oscar-stack/vagrant-auto_network#34]
Sharpie/puppet-debugging-kit/issues/8
Think there might be issue with CentOS 7... 
If I run the oscar stack or puppet-debugging-kit with 
puppetlabs-centos-7.2-64-nocm

The host-only adapter doesn't get the IP address.
If I login to both master and agent early enough in the provisioning process I can run:
`sudo service network restart` and it will get the IP correctly.

**Comment by richburroughs** [comment]
I think this actually isn't Oscar.

I ran into the same thing you described and saw the issue here. Then I started looking into it more and I ran a non-Oscar Vagrant VM I have. I got the same result. The second interface didn't pick up its ip but restarting the network fixed it.

I'm guessing it's either Virtualbox or Vagrant that's causing the issue. I'm going to try downgrading them and see what happens.

**Comment by richburroughs** [comment]
Looks like it's Vagrant. Downgrading to 1.9.0 fixed it for me.

https://github.com/mitchellh/vagrant/issues/8138

**Comment by cdenneen** [comment]
@richburroughs You are correct sir. I've been able to fix the issue with C7 by using vagrant 1.9.0

Thanks for the help

**Comment by Sharpie** [comment]
Yeah, Vagrant support for CentOS 7 networking has been a bit flaky for the past few releases. 1.8.2 was a good release. 1.8.7 is good and is where I'm at for day-to-day usage at the moment. The 1.8.x versions in between have Windows and CentOS issues.

Haven't tried the 1.9.x release series yet.

**Comment by richburroughs** [comment]
@cdenneen No problem, I was looking into this myself which is why I ended up here :)

@Sharpie I'm fine after downgrading to 1.9.0. But yeah Vagrant has had a history of breaking pretty critical features on releases. You are probably best off staying on the older stuff :)
